name: newgps
description: NEW GPS vous permet de tracker vos véhicules en temps réel.
##publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  download: ^0.0.1+1
  editable: ^2.0.0
  faker: ^2.0.0
  firebase_analytics: ^9.3.6
  firebase_core: ^1.22.0
  firebase_dynamic_links: ^4.3.7
  firebase_messaging: ^13.0.2
  firebase_remote_config: ^2.0.18
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.11
  flutter_phoenix: ^1.1.0
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^1.1.5
  flutter_tts: ^3.5.3
  fluttertoast: ^8.1.1
  geolocator: ^9.0.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_maps_cluster_manager: ^3.0.0+1
  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.4.0+3
  grouped_list: ^5.1.2
  http: ^0.13.5
  image: ^3.0.5
  intl: ^0.17.0
  loadmore: ^2.0.1
  month_picker_dialog: ^0.4.0
  provider: ^6.0.3
  restart_app: ^1.1.0+1
  search_choices: ^2.1.1
  share_plus: ^4.2.0
  shared_preferences: ^2.0.15
  syncfusion_flutter_gauges: ^20.2.50
  url_launcher: ^6.1.5
  video_player: ^2.4.7

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  web:
    generate: true
    image_path: "assets/logo-512.png"
    background_color: "#FFFFFF"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/markers/

  fonts:
    - family: speed
      fonts:
        - asset: fonts/icons/speed.ttf
    - family: battery
      fonts:
        - asset: fonts/icons/battery.ttf
    - family: fuel
      fonts:
        - asset: fonts/icons/fuel.ttf
    - family: geozone
      fonts:
        - asset: fonts/icons/geozone.ttf
